version: '3.8'

services:
  web:
    build:
      context: ./Makku_BackEnd_Users
      dockerfile: Dockerfile.prod
    command: gunicorn Makku_BackEnd.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
        - 4449:80
    depends_on:
        - web
volumes:
  postgres_data:
